### ISSUE TITLE
Incorrect Year Range Calculation Results in Inclusion of Nonexistent Data Intervals

### ISSUE THREAD

**Issue by n0rdp0l** [AI4S2S/lilio#74] opened 2024-03-20 10:44 UTC
### Description:

I've discovered a bug that impacts the integrity of dataset resampling, specifically with year range calculations in the presence of boundary (cross year) intervals. The issue occurs in the `_resample_dataset()` function, where `.flat()` retrieves `.get_intervals()`, leading to an incorrect determination of the year range by `_set_year_range_from_timestamps()`. The effect of this bug is the creation of a first interval with a lower bound in (e.g.) 2009 when the dataset only contains data from 2010 onwards.

### Steps to Reproduce:
1. Chose and anchor in the beginning of the year, and a precursor interval that would fall across years.
2. Perform a resampling operation that involves `_resample_dataset()`.
3. Notice the creation of an interval with a lower bound before the dataset's start year (e.g., 2009), despite the data starting in 2010.

### Expected Behavior:
The `_set_year_range_from_timestamps()` function should discard calander intervals that fall outside the available time range of the underlying data.

### Actual Behavior:
The `_set_year_range_from_timestamps()` function currently checks the `.right` bound for minimum years, which leads to the inclusion of intervals where the right bound falls into the year range of our data but the lower bound doesn't.

### Current Code:
```python
def _set_year_range_from_timestamps(self):
    min_year = self._first_timestamp.year  # type: ignore
    max_year = self._last_timestamp.year  # type: ignore

    # ensure that the input data could always cover the advent calendar
    # last date check
    if self._map_year(max_year).iloc[0].right > self._last_timestamp:
        max_year -= 1
    # first date check
    while self._map_year(min_year).iloc[-1].right <= self._first_timestamp:
        min_year += 1
 ```
 ### Proposed change:
```python
def _set_year_range_from_timestamps(self):
    min_year = self._first_timestamp.year  # type: ignore
    max_year = self._last_timestamp.year  # type: ignore

    # ensure that the input data could always cover the advent calendar
    # last date check
    if self._map_year(max_year).iloc[0].right > self._last_timestamp:
        max_year -= 1
    # first date check
    while self._map_year(min_year).iloc[-1].left <= self._first_timestamp:
        min_year += 1
 ```

**Comment by BSchilperoort** [comment] 2024-03-21 07:39
Hi Felix, thanks for submitting this issue.

> The _set_year_range_from_timestamps() function currently checks the .right bound for minimum years, which leads to the inclusion of intervals where the right bound falls into the year range of our data but the lower bound doesn't.

Well that's the intended behavior. There is a data point that falls into the interval.

Lilio compares the time stamps of each data point with the intervals it wants to fill. If your interval is `[2009-12-01, 2010-02-01)`
and you have a data point with the time stamp `2010-01-01`, then there is data available to compute a value for that interval.

I think this is a similar issue to #69. If Lilio was able to compare time _bounds_ with the calendar intervals, an option could be added that can check if the intervals are fully covered.

<hr>

As an example:

![image](https://github.com/AI4S2S/lilio/assets/12114825/e26425d2-6077-4cc4-90b9-57ae774458df)

The red markers are a time series of input data. The vertical purple line is 2010-01-01.
As you see, you can have an interval starting in 2009, while all your data points are in 2010.


<details><summary>Try the code yourself</summary>

```py
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from lilio import Calendar
cal = Calendar("04-01")

cal.add_intervals("target", length="2M")
cal.add_intervals("precursor", length="2M", n=2)

cal.map_years(2010, 2010)
cal.visualize()

dates = pd.date_range("2010-01-01", "2010-06-01", freq="2W")
y = np.zeros(len(dates)) + 2010

plt.plot(dates, y, marker="o", markersize=15, c="red", lw=0)
plt.vlines(x=pd.Timestamp("2010-01-01"), color="magenta", ymin=2000, ymax=3000)
```

</details>

**Comment by BSchilperoort** [comment] 2024-03-21 07:42
If something does go wrong, and it's not the situation described above, could you provide a small piece of code to reproduce the problem?

**Comment by n0rdp0l** [comment] 2024-03-21 16:08
Hey Bart, thanks for your quick reply!
Apologies if I made it seem as if it could only be a bug. I did actually think it might be intended functionality to increase data utilization. 
Maybe to motivate where I was coming from; I was more concerned that it could introduce statistical challenges, particularly when analyzing the effect of different precursor  intervals on the target variable:

1. Variance and Reliability: Differing numbers of data points across intervals can lead to variance discrepancies. Sparse data within an interval may yield less reliable estimates, impacting comparability and consistency.
2. Statistical Power and Bias: Intervals with few data points may not only lack the statistical power needed to detect actual effects, potentially leading to incorrect inferences about effect absence, but also risk introducing bias. If partial intervals fail to fully capture the underlying data trend due to critical missing information, this could skew the analysis, either overestimating or underestimating the true effects.

Introducing an option for users that could ensure intervals are fully covered by the dataset might offer them a way to choose between maximizing data availability and maintaining statistical rigor.

**Comment by BSchilperoort** [comment] 2024-06-10 12:42
Hi Felix, the changes in PR #75 address your issue. 

It turns out there indeed was a bug in the determination of year ranges, which is now fixed.

Additionally, for users that do want to include intervals even if it is technically not fully covered, you can now do:
```py
calendar.map_to_data(..., safe=False)
```

**Closed** 2024-06-11 07:36 UTC
